
// Standalone JavaScript Test Runner for M4 AI Study Harness
// Generated by auditor_m4

function generateUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

function convertStrokesToSvg(strokes, template = 'lined', width = 800, height = 1000) {
  let backgroundElements = `<rect width="100%" height="100%" fill="#FFFFFF"/>`;

  if (template === 'lined') {
    let lines = '';
    for (let y = 60; y < height; y += 32) {
      lines += `<line x1="0" y1="${y}" x2="${width}" y2="${y}" stroke="#E9ECEF" stroke-width="1"/>`;
    }
    backgroundElements += lines;
  } else if (template === 'grid') {
    let grid = '';
    for (let x = 0; x < width; x += 24) {
      grid += `<line x1="${x}" y1="0" x2="${x}" y2="${height}" stroke="#E9ECEF" stroke-width="0.5"/>`;
    }
    for (let y = 0; y < height; y += 24) {
      grid += `<line x1="0" y1="${y}" x2="${width}" y2="${y}" stroke="#E9ECEF" stroke-width="0.5"/>`;
    }
    backgroundElements += grid;
  } else if (template === 'cornell') {
    backgroundElements += `
      <line x1="200" y1="0" x2="200" y2="${height - 150}" stroke="#CED4DA" stroke-width="2"/>
      <line x1="0" y1="${height - 150}" x2="${width}" y2="${height - 150}" stroke="#CED4DA" stroke-width="2"/>
    `;
    for (let y = 60; y < height - 150; y += 32) {
      backgroundElements += `<line x1="200" y1="${y}" x2="${width}" y2="${y}" stroke="#E9ECEF" stroke-width="1"/>`;
    }
  }

  const paths = (strokes || [])
    .map((stroke) => {
      let pathData = stroke.skiaPathSvg;
      if (!pathData && stroke.points && stroke.points.length > 0) {
        if (stroke.points.length === 1) {
          pathData = `M ${stroke.points[0].x} ${stroke.points[0].y} L ${stroke.points[0].x + 0.1} ${stroke.points[0].y + 0.1}`;
        } else {
          pathData = `M ${stroke.points[0].x} ${stroke.points[0].y}` +
            stroke.points.slice(1).map((p) => ` L ${p.x} ${p.y}`).join('');
        }
      }
      if (!pathData) return '';

      const opacity = stroke.tool === 'highlighter' ? 0.4 : 1.0;
      return `<path d="${pathData}" stroke="${stroke.color}" stroke-width="${stroke.size}" fill="none" stroke-linecap="round" stroke-linejoin="round" opacity="${opacity}"/>`;
    })
    .join('\n    ');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <g id="background">
    ${backgroundElements}
  </g>
  <g id="strokes">
    ${paths}
  </g>
</svg>`;
}

class InMemoryStorageRepository {
  constructor() {
    this.notebooks = new Map();
    this.pages = new Map();
    this.strokes = new Map();
    this.studyProfile = {
      subjectTags: ['Mathematics', 'Physics', 'Computer Science'],
      studyHabits: ['Active Recall', 'Spaced Repetition', 'Cornell Method'],
      preferredSummaryFormat: 'bullet',
    };
    this.studyRecaps = new Map();
  }

  async initDatabase() {}

  async createNotebook(title) {
    const now = Date.now();
    const notebook = {
      id: generateUUID(),
      title,
      createdAt: now,
      updatedAt: now,
    };
    this.notebooks.set(notebook.id, notebook);
    await this.createPage(notebook.id, 'lined', 0);
    return notebook;
  }

  async getNotebooks() {
    return Array.from(this.notebooks.values()).sort((a, b) => b.updatedAt - a.updatedAt);
  }

  async getNotebookById(id) {
    return this.notebooks.get(id) || null;
  }

  async updateNotebook(id, updates) {
    const notebook = this.notebooks.get(id);
    if (!notebook) throw new Error(`Notebook with id ${id} not found`);
    if (updates.title !== undefined) {
      notebook.title = updates.title;
    }
    notebook.updatedAt = Date.now();
    this.notebooks.set(id, notebook);
    return notebook;
  }

  async deleteNotebook(id) {
    if (!this.notebooks.has(id)) return;
    const pagesForNotebook = Array.from(this.pages.values()).filter((p) => p.notebookId === id);
    for (const page of pagesForNotebook) {
      await this.deletePageInternal(page.id);
    }
    this.notebooks.delete(id);
  }

  async deletePageInternal(pageId) {
    for (const [strokeId, strokeRecord] of Array.from(this.strokes.entries())) {
      if (strokeRecord.pageId === pageId) {
        this.strokes.delete(strokeId);
      }
    }
    this.pages.delete(pageId);
  }

  async createPage(notebookId, template = 'lined', targetIndex) {
    const existingPages = (await this.getPagesByNotebookId(notebookId)).sort((a, b) => a.pageIndex - b.pageIndex);
    const now = Date.now();

    let insertionIndex = existingPages.length;
    if (targetIndex !== undefined && targetIndex >= 0 && targetIndex <= existingPages.length) {
      insertionIndex = targetIndex;
      for (const page of existingPages) {
        if (page.pageIndex >= insertionIndex) {
          page.pageIndex += 1;
          page.updatedAt = now;
          this.pages.set(page.id, page);
        }
      }
    }

    const newPage = {
      id: generateUUID(),
      notebookId,
      pageIndex: insertionIndex,
      template,
      createdAt: now,
      updatedAt: now,
    };

    this.pages.set(newPage.id, newPage);

    const nb = this.notebooks.get(notebookId);
    if (nb) {
      nb.updatedAt = now;
      this.notebooks.set(notebookId, nb);
    }

    return newPage;
  }

  async getPagesByNotebookId(notebookId) {
    return Array.from(this.pages.values())
      .filter((p) => p.notebookId === notebookId)
      .sort((a, b) => a.pageIndex - b.pageIndex);
  }

  async getPageById(id) {
    return this.pages.get(id) || null;
  }

  async updatePageTemplate(pageId, template) {
    const page = this.pages.get(pageId);
    if (!page) throw new Error(`Page with id ${pageId} not found`);

    const now = Date.now();
    page.template = template;
    page.updatedAt = now;
    this.pages.set(pageId, page);

    const nb = this.notebooks.get(page.notebookId);
    if (nb) {
      nb.updatedAt = now;
      this.notebooks.set(nb.id, nb);
    }

    return page;
  }

  async reorderPages(notebookId, pageIdsInOrder) {
    const now = Date.now();
    pageIdsInOrder.forEach((pageId, index) => {
      const page = this.pages.get(pageId);
      if (page && page.notebookId === notebookId) {
        page.pageIndex = index;
        page.updatedAt = now;
        this.pages.set(pageId, page);
      }
    });

    const nb = this.notebooks.get(notebookId);
    if (nb) {
      nb.updatedAt = now;
      this.notebooks.set(notebookId, nb);
    }

    return this.getPagesByNotebookId(notebookId);
  }

  async deletePage(pageId) {
    const page = this.pages.get(pageId);
    if (!page) return;

    const notebookId = page.notebookId;
    await this.deletePageInternal(pageId);

    const remainingPages = (await this.getPagesByNotebookId(notebookId)).sort((a, b) => a.pageIndex - b.pageIndex);
    const now = Date.now();
    remainingPages.forEach((p, idx) => {
      p.pageIndex = idx;
      p.updatedAt = now;
      this.pages.set(p.id, p);
    });

    const nb = this.notebooks.get(notebookId);
    if (nb) {
      nb.updatedAt = now;
      this.notebooks.set(notebookId, nb);
    }
  }

  async saveStrokesForPage(pageId, strokes) {
    const page = this.pages.get(pageId);
    if (!page) throw new Error(`Page with id ${pageId} not found`);

    await this.deleteStrokesForPage(pageId);

    const now = Date.now();
    strokes.forEach((stroke, idx) => {
      this.strokes.set(stroke.id, {
        ...stroke,
        pageId,
        strokeIndex: idx,
      });
    });

    page.updatedAt = now;
    this.pages.set(pageId, page);

    const nb = this.notebooks.get(page.notebookId);
    if (nb) {
      nb.updatedAt = now;
      this.notebooks.set(page.notebookId, nb);
    }
  }

  async getStrokesByPageId(pageId) {
    return Array.from(this.strokes.values())
      .filter((s) => s.pageId === pageId)
      .sort((a, b) => a.strokeIndex - b.strokeIndex)
      .map(({ pageId: _p, strokeIndex: _i, ...stroke }) => stroke);
  }

  async deleteStrokesForPage(pageId) {
    for (const [strokeId, strokeRecord] of Array.from(this.strokes.entries())) {
      if (strokeRecord.pageId === pageId) {
        this.strokes.delete(strokeId);
      }
    }
  }

  async exportNotebookToJson(notebookId) {
    const notebook = await this.getNotebookById(notebookId);
    if (!notebook) throw new Error(`Notebook with id ${notebookId} not found`);

    const pages = await this.getPagesByNotebookId(notebookId);
    const strokesByPage = {};

    for (const page of pages) {
      strokesByPage[page.id] = await this.getStrokesByPageId(page.id);
    }

    const exportData = {
      version: '1.0',
      exportedAt: Date.now(),
      notebook,
      pages,
      strokesByPage,
    };

    return JSON.stringify(exportData, null, 2);
  }

  async importNotebookFromJson(jsonContent) {
    const data = JSON.parse(jsonContent);
    if (!data.version || !data.notebook || !Array.isArray(data.pages)) {
      throw new Error('Invalid notebook JSON export payload format');
    }

    const now = Date.now();
    let newNotebookId = data.notebook.id;
    if (this.notebooks.has(newNotebookId)) {
      newNotebookId = generateUUID();
    }

    const importedNotebook = {
      id: newNotebookId,
      title: `${data.notebook.title} (Imported)`,
      createdAt: now,
      updatedAt: now,
    };
    this.notebooks.set(importedNotebook.id, importedNotebook);

    for (const oldPage of data.pages) {
      const newPageId = generateUUID();
      const page = {
        id: newPageId,
        notebookId: importedNotebook.id,
        pageIndex: oldPage.pageIndex,
        template: oldPage.template,
        createdAt: now,
        updatedAt: now,
      };
      this.pages.set(page.id, page);

      const oldStrokes = (data.strokesByPage && data.strokesByPage[oldPage.id]) || [];
      const newStrokes = oldStrokes.map((s) => ({
        ...s,
        id: generateUUID(),
      }));
      await this.saveStrokesForPage(page.id, newStrokes);
    }

    return importedNotebook;
  }

  async exportPageAsSvg(pageId, width = 800, height = 1000) {
    const page = await this.getPageById(pageId);
    if (!page) throw new Error(`Page with id ${pageId} not found`);

    const strokes = await this.getStrokesByPageId(pageId);
    return convertStrokesToSvg(strokes, page.template, width, height);
  }

  async getStorageStats() {
    return {
      notebookCount: this.notebooks.size,
      pageCount: this.pages.size,
      strokeCount: this.strokes.size,
    };
  }

  async getStudyProfile() {
    return { ...this.studyProfile };
  }

  async saveStudyProfile(profile) {
    this.studyProfile = {
      subjectTags: [...profile.subjectTags],
      studyHabits: [...profile.studyHabits],
      preferredSummaryFormat: profile.preferredSummaryFormat,
    };
    return { ...this.studyProfile };
  }

  async saveStudyRecap(recap) {
    const recapId = recap.id || generateUUID();
    const savedRecap = {
      ...recap,
      id: recapId,
      generatedAt: recap.generatedAt || Date.now(),
    };
    this.studyRecaps.set(recapId, savedRecap);
    return savedRecap;
  }

  async getLatestRecapByNotebookId(notebookId) {
    const recaps = await this.getRecapsByNotebookId(notebookId);
    return recaps.length > 0 ? recaps[0] : null;
  }

  async getRecapsByNotebookId(notebookId) {
    return Array.from(this.studyRecaps.values())
      .filter((r) => r.notebookId === notebookId)
      .sort((a, b) => b.generatedAt - a.generatedAt);
  }
}

class DatabaseService {
  constructor() {
    this.repo = new InMemoryStorageRepository();
  }
  async initDatabase() {
    await this.repo.initDatabase();
  }
  async createNotebook(title) { return this.repo.createNotebook(title); }
  async getNotebooks() { return this.repo.getNotebooks(); }
  async getNotebookById(id) { return this.repo.getNotebookById(id); }
  async updateNotebook(id, updates) { return this.repo.updateNotebook(id, updates); }
  async deleteNotebook(id) { return this.repo.deleteNotebook(id); }
  async createPage(notebookId, template, targetIndex) { return this.repo.createPage(notebookId, template, targetIndex); }
  async getPagesByNotebookId(notebookId) { return this.repo.getPagesByNotebookId(notebookId); }
  async getPageById(id) { return this.repo.getPageById(id); }
  async updatePageTemplate(pageId, template) { return this.repo.updatePageTemplate(pageId, template); }
  async reorderPages(notebookId, pageIdsInOrder) { return this.repo.reorderPages(notebookId, pageIdsInOrder); }
  async deletePage(pageId) { return this.repo.deletePage(pageId); }
  async saveStrokesForPage(pageId, strokes) { return this.repo.saveStrokesForPage(pageId, strokes); }
  async getStrokesByPageId(pageId) { return this.repo.getStrokesByPageId(pageId); }
  async deleteStrokesForPage(pageId) { return this.repo.deleteStrokesForPage(pageId); }
  async exportNotebookToJson(notebookId) { return this.repo.exportNotebookToJson(notebookId); }
  async importNotebookFromJson(jsonContent) { return this.repo.importNotebookFromJson(jsonContent); }
  async exportPageAsSvg(pageId, width, height) { return this.repo.exportPageAsSvg(pageId, width, height); }
  async getStorageStats() { return this.repo.getStorageStats(); }
  async getStudyProfile() { return this.repo.getStudyProfile(); }
  async saveStudyProfile(profile) { return this.repo.saveStudyProfile(profile); }
  async saveStudyRecap(recap) { return this.repo.saveStudyRecap(recap); }
  async getLatestRecapByNotebookId(notebookId) { return this.repo.getLatestRecapByNotebookId(notebookId); }
  async getRecapsByNotebookId(notebookId) { return this.repo.getRecapsByNotebookId(notebookId); }
}

const databaseService = new DatabaseService();

class StudyAgentHarness {
  constructor(dbRepository) {
    this.db = dbRepository || databaseService;
  }

  async getUserProfile() {
    return this.db.getStudyProfile();
  }

  async updateUserProfile(profile) {
    return this.db.saveStudyProfile(profile);
  }

  async indexNotebookTopics(notebookId, pages = [], strokesInput) {
    let allStrokes = [];
    if (Array.isArray(strokesInput)) {
      allStrokes = strokesInput;
    } else if (strokesInput && typeof strokesInput === 'object') {
      Object.values(strokesInput).forEach((list) => {
        if (Array.isArray(list)) {
          allStrokes.push(...list);
        }
      });
    }

    let activePages = pages;
    if ((!activePages || activePages.length === 0) && notebookId) {
      try {
        activePages = await this.db.getPagesByNotebookId(notebookId);
      } catch (e) {
        activePages = [];
      }
    }

    if (allStrokes.length === 0 && activePages.length > 0) {
      try {
        for (const page of activePages) {
          const st = await this.db.getStrokesByPageId(page.id);
          allStrokes.push(...st);
        }
      } catch (e) {}
    }

    const metrics = {
      totalStrokes: allStrokes.length,
      penStrokes: allStrokes.filter((s) => s.tool === 'pen').length,
      highlighterStrokes: allStrokes.filter((s) => s.tool === 'highlighter').length,
      eraserStrokes: allStrokes.filter((s) => s.tool === 'eraser').length,
      lassoStrokes: allStrokes.filter((s) => s.tool === 'lasso').length,
      templateDistribution: {},
    };

    activePages.forEach((p) => {
      metrics.templateDistribution[p.template] = (metrics.templateDistribution[p.template] || 0) + 1;
    });

    const profile = await this.getUserProfile();

    const topicsMap = new Map();

    const addTopic = (tag, pageId, pageIndex) => {
      const existing = topicsMap.get(tag) || { pageIds: new Set(), pageIndexes: new Set(), count: 0 };
      existing.pageIds.add(pageId);
      existing.pageIndexes.add(pageIndex);
      existing.count += 1;
      topicsMap.set(tag, existing);
    };

    activePages.forEach((page) => {
      if (page.template === 'cornell') {
        addTopic('Cornell Summary & Cues', page.id, page.pageIndex);
        addTopic('Structured Notes', page.id, page.pageIndex);
      } else if (page.template === 'lined') {
        addTopic('Lecture Notes', page.id, page.pageIndex);
      } else if (page.template === 'grid') {
        addTopic('Diagrams & Math', page.id, page.pageIndex);
      } else if (page.template === 'blank') {
        addTopic('Freeform Sketches', page.id, page.pageIndex);
      }
    });

    if (metrics.highlighterStrokes > 0) {
      activePages.forEach((page) => {
        addTopic('Exam High-Yield Focus', page.id, page.pageIndex);
        addTopic('Key Terms & Definitions', page.id, page.pageIndex);
      });
    }

    profile.subjectTags.forEach((tag, idx) => {
      if (activePages.length > 0) {
        const targetPage = activePages[idx % activePages.length];
        addTopic(tag, targetPage.id, targetPage.pageIndex);
      }
    });

    const topics = Array.from(topicsMap.entries()).map(([tag, data]) => {
      const relevanceScore = Math.min(1.0, 0.4 + data.count * 0.2 + (metrics.highlighterStrokes > 0 ? 0.15 : 0));
      return {
        tag,
        pageIds: Array.from(data.pageIds),
        pageIndexes: Array.from(data.pageIndexes).sort((a, b) => a - b),
        relevanceScore: Number(relevanceScore.toFixed(2)),
      };
    });

    const keyConcepts = [];
    if (metrics.templateDistribution['cornell']) {
      keyConcepts.push('Cornell System: Systematic note-taking with dedicated cue and summary sections.');
    }
    if (metrics.highlighterStrokes > 0) {
      keyConcepts.push(`Highlighter Emphasis: ${metrics.highlighterStrokes} key passages flagged for priority review.`);
    }
    if (topics.some((t) => t.tag === 'Diagrams & Math')) {
      keyConcepts.push('Visual Schematics & Equations: Quantitative grid representations.');
    }
    if (profile.subjectTags.length > 0) {
      keyConcepts.push(`Subject Alignment: Correlated with ${profile.subjectTags.join(', ')}.`);
    }
    if (keyConcepts.length === 0) {
      keyConcepts.push('General Overview: Handwritten vector strokes captured for topic analysis.');
    }

    return {
      notebookId,
      topics,
      keyConcepts,
      metrics,
    };
  }

  async generateRecap(notebookId, pages = [], strokesInput) {
    const profile = await this.getUserProfile();
    const topicIndex = await this.indexNotebookTopics(notebookId, pages, strokesInput);
    const { topics, keyConcepts, metrics } = topicIndex;

    const totalPages = pages.length > 0 ? pages.length : 1;
    const format = profile.preferredSummaryFormat || 'bullet';

    let summaryText = '';
    const actionItems = [];

    if (format === 'bullet') {
      summaryText = [
        `• Notebook Overview: Analyzed ${totalPages} pages containing ${metrics.totalStrokes} total handwritten vector strokes.`,
        `• Active Tools: ${metrics.penStrokes} pen strokes, ${metrics.highlighterStrokes} highlighter highlights.`,
        `• Primary Layout Templates: ${Object.entries(metrics.templateDistribution)
          .map(([tpl, count]) => `${tpl} (${count})`)
          .join(', ') || 'lined (1)'}.`,
        `• Identified Topics: ${topics.map((t) => t.tag).slice(0, 4).join(', ') || 'General Notes'}.`,
        `• Key Takeaway: ${keyConcepts[0] || 'Structured notes ready for active recall review.'}`,
      ].join('\n');

      actionItems.push(`Review ${metrics.highlighterStrokes} highlighted sections across pages.`);
      actionItems.push(`Complete self-quiz on ${topics[0]?.tag || 'core topics'}.`);
      actionItems.push(`Schedule spaced repetition session in 48 hours.`);
    } else if (format === 'executive') {
      summaryText = [
        `[EXECUTIVE STUDY SUMMARY]`,
        ``,
        `EXECUTIVE BRIEF: Notebook ${notebookId.slice(0, 8)} contains ${totalPages} page(s) with ${metrics.totalStrokes} vector stroke entries.`,
        `ANALYSIS & INSIGHTS: Primary layout utilizes ${Object.keys(metrics.templateDistribution).join('/') || 'lined'} paper. ` +
          `Highlighter intensity is at ${metrics.highlighterStrokes} markers, indicating key focus areas.`,
        `TOPIC SYNOPSIS: Subject coverage includes ${topics.map((t) => t.tag).join('; ') || 'General Study'}.`,
        `RECOMMENDATION: Executive recommendation is to focus active study efforts on high-relevance topics and convert summary cues into flashcard sets.`,
      ].join('\n');

      actionItems.push(`Execute priority review of executive key concepts.`);
      actionItems.push(`Validate top-relevance topic tags against upcoming syllabus milestones.`);
      actionItems.push(`Synthesize multi-page notes into an executive study briefing.`);
    } else if (format === 'flashcard') {
      summaryText = [
        `[FLASHCARD 1]`,
        `Front: What is the main subject focus of this notebook?`,
        `Back: ${topics.map((t) => t.tag).slice(0, 3).join(', ') || 'General Study Notes'}.`,
        ``,
        `[FLASHCARD 2]`,
        `Front: What are the key concepts recorded?`,
        `Back: ${keyConcepts.slice(0, 2).join(' | ')}.`,
        ``,
        `[FLASHCARD 3]`,
        `Front: What stroke metrics and study habits apply?`,
        `Back: ${metrics.totalStrokes} total strokes (${metrics.highlighterStrokes} highlighted). Habits: ${profile.studyHabits.join(', ')}.`,
      ].join('\n');

      actionItems.push(`Flashcard Deck: Practice Flashcard 1 (Subject Topics).`);
      actionItems.push(`Flashcard Deck: Master Flashcard 2 (Key Concepts).`);
      actionItems.push(`Flashcard Deck: Test speed-recall on Flashcard 3 (Metrics & Habits).`);
    }

    const recap = {
      notebookId,
      summaryText,
      keyConcepts,
      actionItems,
      generatedAt: Date.now(),
    };

    const savedRecap = await this.db.saveStudyRecap(recap);
    return savedRecap;
  }

  async getLatestRecap(notebookId) {
    return this.db.getLatestRecapByNotebookId(notebookId);
  }

  async getRecapHistory(notebookId) {
    return this.db.getRecapsByNotebookId(notebookId);
  }
}

// -------------------------------------------------------------
// Test Runner Harness
// -------------------------------------------------------------

let currentBeforeEach = null;
const testsToRun = [];
let currentSuite = 'Global';

function describe(suiteName, fn) {
  currentSuite = suiteName;
  fn();
}

function beforeEach(fn) {
  currentBeforeEach = fn;
}

function test(testName, fn) {
  testsToRun.push({
    suite: currentSuite,
    name: testName,
    fn,
    beforeEach: currentBeforeEach,
  });
}

function expect(actual) {
  return {
    toBeDefined: () => {
      if (actual === undefined) throw new Error(`Expected value to be defined, but got undefined`);
    },
    toBeNull: () => {
      if (actual !== null) throw new Error(`Expected null, but got ${JSON.stringify(actual)}`);
    },
    toNotBeNull: () => {
      if (actual === null || actual === undefined) throw new Error(`Expected non-null value, but got ${JSON.stringify(actual)}`);
    },
    toBe: (expected) => {
      if (actual !== expected) throw new Error(`Expected ${JSON.stringify(expected)}, but got ${JSON.stringify(actual)}`);
    },
    toEqual: (expected) => {
      const actualJson = JSON.stringify(actual);
      const expectedJson = JSON.stringify(expected);
      if (actualJson !== expectedJson) throw new Error(`Expected ${expectedJson}, but got ${actualJson}`);
    },
    toContain: (expected) => {
      if (typeof actual === 'string') {
        if (!actual.includes(expected)) {
          throw new Error(`Expected string to contain ${JSON.stringify(expected)}, but got ${JSON.stringify(actual)}`);
        }
      } else if (Array.isArray(actual)) {
        if (!actual.includes(expected)) {
          throw new Error(`Expected array to contain ${JSON.stringify(expected)}, but got ${JSON.stringify(actual)}`);
        }
      } else {
        throw new Error(`Expected string or array, but got ${typeof actual}`);
      }
    },
    toBeGreaterThan: (expected) => {
      if (typeof actual !== 'number' || actual <= expected) {
        throw new Error(`Expected ${actual} to be greater than ${expected}`);
      }
    },
    toBeLessThanOrEqual: (expected) => {
      if (typeof actual !== 'number' || actual > expected) {
        throw new Error(`Expected ${actual} to be less than or equal to ${expected}`);
      }
    },
    toBeGreaterThanOrEqual: (expected) => {
      if (typeof actual !== 'number' || actual < expected) {
        throw new Error(`Expected ${actual} to be greater than or equal to ${expected}`);
      }
    },
    get not() {
      return {
        toBeNull: () => {
          if (actual === null) throw new Error(`Expected value not to be null`);
        },
      };
    },
  };
}

// -------------------------------------------------------------
// Official M4 Unit Tests (from StudyAgentHarness.test.ts)
// -------------------------------------------------------------

describe('StudyAgentHarness Unit Tests', () => {
  let repo;
  let harness;

  beforeEach(async () => {
    repo = new InMemoryStorageRepository();
    await repo.initDatabase();
    harness = new StudyAgentHarness(repo);
  });

  test('getUserProfile returns default profile and updateUserProfile persists updates', async () => {
    const initialProfile = await harness.getUserProfile();
    expect(initialProfile).toBeDefined();
    expect(Array.isArray(initialProfile.subjectTags)).toBe(true);
    expect(initialProfile.preferredSummaryFormat).toBe('bullet');

    const updatedProf = {
      subjectTags: ['Quantum Mechanics', 'Linear Algebra'],
      studyHabits: ['Pomodoro 25/5', 'Feynman Technique'],
      preferredSummaryFormat: 'executive',
    };

    const saved = await harness.updateUserProfile(updatedProf);
    expect(saved.subjectTags).toEqual(['Quantum Mechanics', 'Linear Algebra']);
    expect(saved.preferredSummaryFormat).toBe('executive');

    const retrieved = await harness.getUserProfile();
    expect(retrieved.subjectTags).toEqual(['Quantum Mechanics', 'Linear Algebra']);
    expect(retrieved.preferredSummaryFormat).toBe('executive');
  });

  test('indexNotebookTopics extracts topics, key concepts, and stroke metrics correctly', async () => {
    const pages = [
      { id: 'page-1', notebookId: 'nb-101', pageIndex: 0, template: 'cornell', createdAt: 100, updatedAt: 100 },
      { id: 'page-2', notebookId: 'nb-101', pageIndex: 1, template: 'grid', createdAt: 200, updatedAt: 200 },
    ];

    const strokes = [
      { id: 's1', tool: 'pen', color: '#000', size: 3, points: [{ x: 10, y: 10 }], createdAt: 100 },
      { id: 's2', tool: 'pen', color: '#000', size: 3, points: [{ x: 20, y: 20 }], createdAt: 110 },
      { id: 's3', tool: 'highlighter', color: '#FF0', size: 15, points: [{ x: 50, y: 50 }], createdAt: 120 },
    ];

    const topicIndex = await harness.indexNotebookTopics('nb-101', pages, strokes);
    expect(topicIndex.notebookId).toBe('nb-101');
    expect(topicIndex.metrics.totalStrokes).toBe(3);
    expect(topicIndex.metrics.penStrokes).toBe(2);
    expect(topicIndex.metrics.highlighterStrokes).toBe(1);
    expect(topicIndex.metrics.templateDistribution['cornell']).toBe(1);
    expect(topicIndex.metrics.templateDistribution['grid']).toBe(1);

    const tags = topicIndex.topics.map((t) => t.tag);
    expect(tags).toContain('Cornell Summary & Cues');
    expect(tags).toContain('Diagrams & Math');
    expect(tags).toContain('Exam High-Yield Focus');

    expect(topicIndex.topics[0].relevanceScore).toBeGreaterThan(0);
    expect(topicIndex.keyConcepts.length).toBeGreaterThan(0);
  });

  test('generateRecap produces bullet format summary and persists to DB', async () => {
    await harness.updateUserProfile({
      subjectTags: ['Physics'],
      studyHabits: ['Active Recall'],
      preferredSummaryFormat: 'bullet',
    });

    const pages = [
      { id: 'p1', notebookId: 'nb-bullet', pageIndex: 0, template: 'lined', createdAt: 100, updatedAt: 100 },
    ];
    const strokes = [
      { id: 's1', tool: 'pen', color: '#000', size: 2, points: [{ x: 0, y: 0 }], createdAt: 100 },
    ];

    const recap = await harness.generateRecap('nb-bullet', pages, strokes);
    expect(recap.notebookId).toBe('nb-bullet');
    expect(recap.summaryText).toContain('• Notebook Overview:');
    expect(recap.summaryText).toContain('• Primary Layout Templates:');
    expect(recap.keyConcepts.length).toBeGreaterThan(0);
    expect(recap.actionItems.length).toBeGreaterThan(0);

    const latest = await harness.getLatestRecap('nb-bullet');
    expect(latest).not.toBeNull();
    expect(latest?.summaryText).toBe(recap.summaryText);
  });

  test('generateRecap produces executive format summary', async () => {
    await harness.updateUserProfile({
      subjectTags: ['Economics'],
      studyHabits: ['Executive Briefing'],
      preferredSummaryFormat: 'executive',
    });

    const pages = [
      { id: 'p1', notebookId: 'nb-exec', pageIndex: 0, template: 'cornell', createdAt: 100, updatedAt: 100 },
    ];

    const recap = await harness.generateRecap('nb-exec', pages, []);
    expect(recap.summaryText).toContain('[EXECUTIVE STUDY SUMMARY]');
    expect(recap.summaryText).toContain('EXECUTIVE BRIEF:');
    expect(recap.summaryText).toContain('RECOMMENDATION:');
    expect(recap.actionItems[0]).toContain('Execute priority review');
  });

  test('generateRecap produces flashcard format summary', async () => {
    await harness.updateUserProfile({
      subjectTags: ['Biology'],
      studyHabits: ['Flashcards'],
      preferredSummaryFormat: 'flashcard',
    });

    const pages = [
      { id: 'p1', notebookId: 'nb-flash', pageIndex: 0, template: 'lined', createdAt: 100, updatedAt: 100 },
    ];

    const recap = await harness.generateRecap('nb-flash', pages, []);
    expect(recap.summaryText).toContain('[FLASHCARD 1]');
    expect(recap.summaryText).toContain('Front:');
    expect(recap.summaryText).toContain('Back:');
    expect(recap.actionItems[0]).toContain('Flashcard Deck:');
  });

  test('Recap Database Retrieval gets latest and recap history in chronological DESC order', async () => {
    const notebookId = 'nb-history';
    const pages = [
      { id: 'p1', notebookId, pageIndex: 0, template: 'lined', createdAt: 100, updatedAt: 100 },
    ];

    const r1 = await harness.generateRecap(notebookId, pages, []);
    await new Promise((r) => setTimeout(r, 15));

    const r2 = await harness.generateRecap(notebookId, pages, []);

    const history = await harness.getRecapHistory(notebookId);
    expect(history.length).toBe(2);
    expect(history[0].generatedAt).toBeGreaterThanOrEqual(history[1].generatedAt);

    const latest = await harness.getLatestRecap(notebookId);
    expect(latest?.generatedAt).toBe(r2.generatedAt);
  });
});

// -------------------------------------------------------------
// Challenger M4 Stress Tests
// -------------------------------------------------------------

describe('Challenger M4 Stress & Edge Case Tests', () => {
  test('Profile Update with Empty Arrays (subjectTags: [], studyHabits: [])', async () => {
    const repo = new InMemoryStorageRepository();
    await repo.initDatabase();
    const harness = new StudyAgentHarness(repo);

    const emptyProfile = {
      subjectTags: [],
      studyHabits: [],
      preferredSummaryFormat: 'bullet',
    };

    const updated = await harness.updateUserProfile(emptyProfile);
    expect(updated.subjectTags).toEqual([]);
    expect(updated.studyHabits).toEqual([]);

    const retrieved = await harness.getUserProfile();
    expect(retrieved.subjectTags).toEqual([]);
    expect(retrieved.studyHabits).toEqual([]);
  });

  test('Topic Indexing with Empty Page Lists & Empty DB Fallback', async () => {
    const repo = new InMemoryStorageRepository();
    await repo.initDatabase();
    const harness = new StudyAgentHarness(repo);

    const topicIndex = await harness.indexNotebookTopics('nb-empty', [], []);
    expect(topicIndex.notebookId).toBe('nb-empty');
    expect(topicIndex.topics).toEqual([]);
    expect(topicIndex.metrics.totalStrokes).toBe(0);
    expect(topicIndex.keyConcepts.length).toBeGreaterThan(0);
  });

  test('Topic Indexing with Large Page Lists (150 pages) and Performance Check', async () => {
    const repo = new InMemoryStorageRepository();
    await repo.initDatabase();
    const harness = new StudyAgentHarness(repo);

    await harness.updateUserProfile({
      subjectTags: ['TagA', 'TagB', 'TagC'],
      studyHabits: ['Habit1'],
      preferredSummaryFormat: 'bullet',
    });

    const largePages = [];
    for (let i = 0; i < 150; i++) {
      largePages.push({
        id: `p-${i}`,
        notebookId: 'nb-large',
        pageIndex: i,
        template: i % 4 === 0 ? 'cornell' : i % 4 === 1 ? 'lined' : i % 4 === 2 ? 'grid' : 'blank',
        createdAt: 1000 + i,
        updatedAt: 1000 + i,
      });
    }

    const startTime = Date.now();
    const topicIndex = await harness.indexNotebookTopics('nb-large', largePages, []);
    const duration = Date.now() - startTime;

    expect(duration).toBeLessThanOrEqual(1000);
    expect(topicIndex.metrics.templateDistribution['cornell']).toBe(38);
    expect(topicIndex.metrics.templateDistribution['lined']).toBe(38);
    expect(topicIndex.metrics.templateDistribution['grid']).toBe(37);
    expect(topicIndex.metrics.templateDistribution['blank']).toBe(37);
  });
});

// Main execution function
async function main() {
  console.log(`\n======================================================`);
  console.log(` Running M4 AI Study Harness Tests (${testsToRun.length} tests)`);
  console.log(`======================================================\n`);

  let passed = 0;
  let failed = 0;
  const startTime = Date.now();

  for (const t of testsToRun) {
    try {
      if (t.beforeEach) {
        await t.beforeEach();
      }
      await t.fn();
      console.log(`  ✓ [PASS] ${t.suite} > ${t.name}`);
      passed++;
    } catch (err) {
      console.error(`  ✗ [FAIL] ${t.suite} > ${t.name}`);
      console.error(`     Error: ${err?.message || err}\n`);
      failed++;
    }
  }

  const duration = Date.now() - startTime;
  console.log(`\n------------------------------------------------------`);
  console.log(` Summary: ${passed} passed, ${failed} failed | Time: ${duration}ms`);
  console.log(`------------------------------------------------------\n`);

  if (failed > 0) {
    process.exit(1);
  }
}

main();
